#ifndef CONFIG_H_MAIN_FILE
#define CONFIG_H_MAIN_FILE

#define HTTP_SERVER_PORT 8085

#define PROJECT_ROOT "/home/nita/dev/c/change2/"

#define DEFAULT_MOCK_DIRECTORY PROJECT_ROOT "mocks/"
#define DEFAULT_GRAPH_EXPORT PROJECT_ROOT "js/export.json"

#define CONFIG_STR(x) #x
#define CONFIG_XSTR(x) CONFIG_STR(x)

#define DEFAULT_MOCK_NODES_COUNT 12
#define DEFAULT_MOCK_ACTIONS_COUNT 20

#define MAX_INPUT_SIZE 2048

#endif
