#ifndef INPUT_PROCESSOR_C
#define INPUT_PROCESSOR_C

#include "../lib/util/util.h"

// TODO : This is a fixed prompt, if you want to customize init node activation / weight, you have to modify the prompt separate 
#define DECOMPOSITION_INTO_GRAPH_PROMPT "You are analyzing a single user input and decomposing it into a semantic identity graph across five psychological contexts. The input text is: [%s]. The purpose is to transform the user input into a structured graph representation of the user's internal identity, motivations, emotions, passions, general tendencies, and subjective interpretations. This graph will later be traversed by an AI investigation engine. You must analyze the same input through exactly these five contexts: profesie, emotie, pasiuni, generalitati, subiectiv. Return one single valid JSON object and nothing else. Do not output markdown. Do not output explanations. Do not output commentary. The root JSON object must contain exactly these five top-level keys and no others: profesie, emotie, pasiuni, generalitati, subiectiv. Each of these five keys must map to an object containing exactly these keys: nodes, connections. Do not include a nested context field inside those objects, because the context is already represented by the top-level key. For each context object, nodes must be an array of semantic concepts relevant to that context, and connections must be an array of meaningful relations between nodes from the same context. Each node must contain a string field named name. Each node may also contain numeric fields named weight and activation. Weight should usually stay close to 1 with small variation. Activation should usually stay close to 1 but may occasionally spike when a concept is especially salient in the input. Each connection must contain a field named nodes which is an array of exactly two node names that exist in the same context object. Each connection may also contain numeric fields named weight and activation. Generate around 8 relevant nodes per context when enough information exists. Generate around 8 relevant connections per context when enough information exists. If the input provides little information for a context, return fewer but still relevant nodes and connections. Rules: Use short lowercase node names. Avoid duplicates within the same context. Do not invent unrelated concepts. Stay faithful to the user input. Prefer semantically meaningful abstractions over copying long phrases from the input. Keep each context distinct, but mild overlap of concepts is allowed when justified by the input. Connections must be meaningful, not random. Return only JSON."

#define OPENAI_DECOMPOSITION_SCHEMA_JSON \
"{" \
  "\"type\":\"object\"," \
  "\"additionalProperties\":false," \
  "\"required\":[\"profesie\",\"emotie\",\"pasiuni\",\"generalitati\",\"subiectiv\"]," \
  "\"properties\":{" \
    "\"profesie\":{" \
      "\"type\":\"object\"," \
      "\"additionalProperties\":false," \
      "\"required\":[\"nodes\",\"connections\"]," \
      "\"properties\":{" \
        "\"nodes\":{" \
          "\"type\":\"array\"," \
          "\"items\":{" \
            "\"type\":\"object\"," \
            "\"additionalProperties\":false," \
            "\"required\":[\"name\",\"weight\",\"activation\"]," \
            "\"properties\":{" \
              "\"name\":{\"type\":\"string\"}," \
              "\"weight\":{\"type\":[\"number\",\"null\"]}," \
              "\"activation\":{\"type\":[\"number\",\"null\"]}" \
            "}" \
          "}" \
        "}," \
        "\"connections\":{" \
          "\"type\":\"array\"," \
          "\"items\":{" \
            "\"type\":\"object\"," \
            "\"additionalProperties\":false," \
            "\"required\":[\"nodes\",\"weight\",\"activation\"]," \
            "\"properties\":{" \
              "\"nodes\":{" \
                "\"type\":\"array\"," \
                "\"minItems\":2," \
                "\"maxItems\":2," \
                "\"items\":{\"type\":\"string\"}" \
              "}," \
              "\"weight\":{\"type\":[\"number\",\"null\"]}," \
              "\"activation\":{\"type\":[\"number\",\"null\"]}" \
            "}" \
          "}" \
        "}" \
      "}" \
    "}," \
    "\"emotie\":{" \
      "\"type\":\"object\"," \
      "\"additionalProperties\":false," \
      "\"required\":[\"nodes\",\"connections\"]," \
      "\"properties\":{" \
        "\"nodes\":{" \
          "\"type\":\"array\"," \
          "\"items\":{" \
            "\"type\":\"object\"," \
            "\"additionalProperties\":false," \
            "\"required\":[\"name\",\"weight\",\"activation\"]," \
            "\"properties\":{" \
              "\"name\":{\"type\":\"string\"}," \
              "\"weight\":{\"type\":[\"number\",\"null\"]}," \
              "\"activation\":{\"type\":[\"number\",\"null\"]}" \
            "}" \
          "}" \
        "}," \
        "\"connections\":{" \
          "\"type\":\"array\"," \
          "\"items\":{" \
            "\"type\":\"object\"," \
            "\"additionalProperties\":false," \
            "\"required\":[\"nodes\",\"weight\",\"activation\"]," \
            "\"properties\":{" \
              "\"nodes\":{" \
                "\"type\":\"array\"," \
                "\"minItems\":2," \
                "\"maxItems\":2," \
                "\"items\":{\"type\":\"string\"}" \
              "}," \
              "\"weight\":{\"type\":[\"number\",\"null\"]}," \
              "\"activation\":{\"type\":[\"number\",\"null\"]}" \
            "}" \
          "}" \
        "}" \
      "}" \
    "}," \
    "\"pasiuni\":{" \
      "\"type\":\"object\"," \
      "\"additionalProperties\":false," \
      "\"required\":[\"nodes\",\"connections\"]," \
      "\"properties\":{" \
        "\"nodes\":{" \
          "\"type\":\"array\"," \
          "\"items\":{" \
            "\"type\":\"object\"," \
            "\"additionalProperties\":false," \
            "\"required\":[\"name\",\"weight\",\"activation\"]," \
            "\"properties\":{" \
              "\"name\":{\"type\":\"string\"}," \
              "\"weight\":{\"type\":[\"number\",\"null\"]}," \
              "\"activation\":{\"type\":[\"number\",\"null\"]}" \
            "}" \
          "}" \
        "}," \
        "\"connections\":{" \
          "\"type\":\"array\"," \
          "\"items\":{" \
            "\"type\":\"object\"," \
            "\"additionalProperties\":false," \
            "\"required\":[\"nodes\",\"weight\",\"activation\"]," \
            "\"properties\":{" \
              "\"nodes\":{" \
                "\"type\":\"array\"," \
                "\"minItems\":2," \
                "\"maxItems\":2," \
                "\"items\":{\"type\":\"string\"}" \
              "}," \
              "\"weight\":{\"type\":[\"number\",\"null\"]}," \
              "\"activation\":{\"type\":[\"number\",\"null\"]}" \
            "}" \
          "}" \
        "}" \
      "}" \
    "}," \
    "\"generalitati\":{" \
      "\"type\":\"object\"," \
      "\"additionalProperties\":false," \
      "\"required\":[\"nodes\",\"connections\"]," \
      "\"properties\":{" \
        "\"nodes\":{" \
          "\"type\":\"array\"," \
          "\"items\":{" \
            "\"type\":\"object\"," \
            "\"additionalProperties\":false," \
            "\"required\":[\"name\",\"weight\",\"activation\"]," \
            "\"properties\":{" \
              "\"name\":{\"type\":\"string\"}," \
              "\"weight\":{\"type\":[\"number\",\"null\"]}," \
              "\"activation\":{\"type\":[\"number\",\"null\"]}" \
            "}" \
          "}" \
        "}," \
        "\"connections\":{" \
          "\"type\":\"array\"," \
          "\"items\":{" \
            "\"type\":\"object\"," \
            "\"additionalProperties\":false," \
            "\"required\":[\"nodes\",\"weight\",\"activation\"]," \
            "\"properties\":{" \
              "\"nodes\":{" \
                "\"type\":\"array\"," \
                "\"minItems\":2," \
                "\"maxItems\":2," \
                "\"items\":{\"type\":\"string\"}" \
              "}," \
              "\"weight\":{\"type\":[\"number\",\"null\"]}," \
              "\"activation\":{\"type\":[\"number\",\"null\"]}" \
            "}" \
          "}" \
        "}" \
      "}" \
    "}," \
    "\"subiectiv\":{" \
      "\"type\":\"object\"," \
      "\"additionalProperties\":false," \
      "\"required\":[\"nodes\",\"connections\"]," \
      "\"properties\":{" \
        "\"nodes\":{" \
          "\"type\":\"array\"," \
          "\"items\":{" \
            "\"type\":\"object\"," \
            "\"additionalProperties\":false," \
            "\"required\":[\"name\",\"weight\",\"activation\"]," \
            "\"properties\":{" \
              "\"name\":{\"type\":\"string\"}," \
              "\"weight\":{\"type\":[\"number\",\"null\"]}," \
              "\"activation\":{\"type\":[\"number\",\"null\"]}" \
            "}" \
          "}" \
        "}," \
        "\"connections\":{" \
          "\"type\":\"array\"," \
          "\"items\":{" \
            "\"type\":\"object\"," \
            "\"additionalProperties\":false," \
            "\"required\":[\"nodes\",\"weight\",\"activation\"]," \
            "\"properties\":{" \
              "\"nodes\":{" \
                "\"type\":\"array\"," \
                "\"minItems\":2," \
                "\"maxItems\":2," \
                "\"items\":{\"type\":\"string\"}" \
              "}," \
              "\"weight\":{\"type\":[\"number\",\"null\"]}," \
              "\"activation\":{\"type\":[\"number\",\"null\"]}" \
            "}" \
          "}" \
        "}" \
      "}" \
    "}" \
  "}" \
"}"


void DecomposeInputIntoGraph(String *input);

#endif
