#ifndef INPUT_PROCESSOR_C
#define INPUT_PROCESSOR_C

#include "util.h"

#define DECOMPOSITION_INTO_GRAPH_PROMPT "You are analyzing a single user input and decomposing it into a semantic identity graph across five psychological contexts. The input text is: [%s]. The goal is to transform the input into a structured graph representation of the user's identity, motivations, emotions, passions, general tendencies, and subjective interpretations. This graph will later be traversed by an AI investigation engine. Return exactly one valid JSON object and nothing else. Do not output markdown. Do not output explanations. Do not output commentary. The root JSON object must contain exactly these five top-level keys and no others: profesie, emotie, pasiuni, generalitati, subiectiv. Each of these five keys must map to an object containing exactly these keys: nodes, connections. For each context object: nodes must be an array of semantic concepts relevant to that context, and connections must be an array of meaningful relations between nodes from the same context. Node rules: each node must contain a string field named \"name\". Each node may also contain numeric fields named \"weight\" and \"activation\". Weight should usually stay near 1.0, with small variation. Activation should usually stay near 1.0, but may be higher for especially salient concepts. Prefer around 8 nodes per context when enough information exists. If evidence is sparse, return fewer nodes, but still include plausible low-confidence inferred nodes when justified. Node naming constraints: node names must be lowercase, short, and canonical. Maximum length is 32 characters. Use only letters and spaces. Do not use quotes, apostrophes, punctuation, underscores, hyphens, or special characters. Do not include characters like \\\" or any other quoting marks inside names. Use plain spaces between words only. Prefer single-word names; use two words only if necessary. Remove articles, determiners, pronouns, and filler words. Avoid phrases like \"the house\", \"a career\", \"my fear\"; use \"house\", \"career\", \"fear\". Avoid plurals when a singular base form expresses the concept. Avoid inflected or conjugated forms when a simpler base form exists. Merge candidates that differ only by plurality, tense, or minor wording variation. Avoid duplicate or near-synonym nodes unless they carry clearly distinct meanings. Connection rules: each connection must contain a field named \"nodes\" which is an array of exactly two node names that exist in the same context object. Each connection may also contain numeric fields named \"weight\" and \"activation\". Prefer around 8 connections per context when enough information exists. Do not create all possible pairwise connections. Do create enough connections so the graph is meaningfully traversable and not overly sparse. Prefer connections between semantically central, causally related, emotionally related, or mutually reinforcing nodes. If a node is important, try to connect it to multiple relevant nodes instead of leaving it isolated. Inference rules: stay faithful to the user input, but you are encouraged to make cautious semantic inferences. Inferred concepts are allowed even if not explicitly stated, as long as they are reasonably supported by tone, wording, implication, or context. Inferred concepts should usually have slightly lower weight than directly supported concepts. When uncertain, prefer adding a useful low-confidence node or connection rather than omitting a likely concept entirely. Do not invent unrelated concepts; every inferred concept must remain plausibly grounded in the input. Directly supported concepts should usually have weight around 0.95 to 1.15. Inferred but plausible concepts should usually have weight around 0.65 to 0.9. Weakly inferred connections should usually have lower weight than explicit ones. Mild overlap across contexts is allowed when justified, but each context should remain distinct. Graph construction rules: prioritize semantic abstractions over copying long phrases from the input. Include central concepts first, then secondary concepts, then cautious inferred concepts. Connections must be meaningful, not random. Favor graphs with local structure, hubs, and semantically coherent clusters. Avoid disconnected node lists unless the input truly provides no basis for relations. If enough information exists, most nodes should participate in at least one connection. When enough information exists, aim for a moderately dense graph where central nodes may have degree 2 to 4, while peripheral nodes may have degree 1. Do not connect nodes merely because they co-occur in the text; connect them only when there is a plausible semantic relation. Output schema requirements: each top-level context object must contain exactly: nodes, connections. Each node object must contain name and may contain weight and activation. Each connection object must contain nodes and may contain weight and activation. Each connection nodes array must contain exactly two valid node names from the same context. Return only JSON."

#define OPENAI_DECOMPOSITION_SCHEMA_JSON \
"{" \
  "\"type\":\"object\"," \
  "\"additionalProperties\":false," \
  "\"required\":[\"profesie\",\"emotie\",\"pasiuni\",\"generalitati\",\"subiectiv\"]," \
  "\"properties\":{" \
    "\"profesie\":{" \
      "\"type\":\"object\"," \
      "\"additionalProperties\":false," \
      "\"required\":[\"nodes\",\"connections\"]," \
      "\"properties\":{" \
        "\"nodes\":{" \
          "\"type\":\"array\"," \
          "\"items\":{" \
            "\"type\":\"object\"," \
            "\"additionalProperties\":false," \
            "\"required\":[\"name\",\"weight\",\"activation\"]," \
            "\"properties\":{" \
              "\"name\":{\"type\":\"string\"}," \
              "\"weight\":{\"type\":[\"number\",\"null\"]}," \
              "\"activation\":{\"type\":[\"number\",\"null\"]}" \
            "}" \
          "}" \
        "}," \
        "\"connections\":{" \
          "\"type\":\"array\"," \
          "\"items\":{" \
            "\"type\":\"object\"," \
            "\"additionalProperties\":false," \
            "\"required\":[\"nodes\",\"weight\",\"activation\"]," \
            "\"properties\":{" \
              "\"nodes\":{" \
                "\"type\":\"array\"," \
                "\"minItems\":2," \
                "\"maxItems\":2," \
                "\"items\":{\"type\":\"string\"}" \
              "}," \
              "\"weight\":{\"type\":[\"number\",\"null\"]}," \
              "\"activation\":{\"type\":[\"number\",\"null\"]}" \
            "}" \
          "}" \
        "}" \
      "}" \
    "}," \
    "\"emotie\":{" \
      "\"type\":\"object\"," \
      "\"additionalProperties\":false," \
      "\"required\":[\"nodes\",\"connections\"]," \
      "\"properties\":{" \
        "\"nodes\":{" \
          "\"type\":\"array\"," \
          "\"items\":{" \
            "\"type\":\"object\"," \
            "\"additionalProperties\":false," \
            "\"required\":[\"name\",\"weight\",\"activation\"]," \
            "\"properties\":{" \
              "\"name\":{\"type\":\"string\"}," \
              "\"weight\":{\"type\":[\"number\",\"null\"]}," \
              "\"activation\":{\"type\":[\"number\",\"null\"]}" \
            "}" \
          "}" \
        "}," \
        "\"connections\":{" \
          "\"type\":\"array\"," \
          "\"items\":{" \
            "\"type\":\"object\"," \
            "\"additionalProperties\":false," \
            "\"required\":[\"nodes\",\"weight\",\"activation\"]," \
            "\"properties\":{" \
              "\"nodes\":{" \
                "\"type\":\"array\"," \
                "\"minItems\":2," \
                "\"maxItems\":2," \
                "\"items\":{\"type\":\"string\"}" \
              "}," \
              "\"weight\":{\"type\":[\"number\",\"null\"]}," \
              "\"activation\":{\"type\":[\"number\",\"null\"]}" \
            "}" \
          "}" \
        "}" \
      "}" \
    "}," \
    "\"pasiuni\":{" \
      "\"type\":\"object\"," \
      "\"additionalProperties\":false," \
      "\"required\":[\"nodes\",\"connections\"]," \
      "\"properties\":{" \
        "\"nodes\":{" \
          "\"type\":\"array\"," \
          "\"items\":{" \
            "\"type\":\"object\"," \
            "\"additionalProperties\":false," \
            "\"required\":[\"name\",\"weight\",\"activation\"]," \
            "\"properties\":{" \
              "\"name\":{\"type\":\"string\"}," \
              "\"weight\":{\"type\":[\"number\",\"null\"]}," \
              "\"activation\":{\"type\":[\"number\",\"null\"]}" \
            "}" \
          "}" \
        "}," \
        "\"connections\":{" \
          "\"type\":\"array\"," \
          "\"items\":{" \
            "\"type\":\"object\"," \
            "\"additionalProperties\":false," \
            "\"required\":[\"nodes\",\"weight\",\"activation\"]," \
            "\"properties\":{" \
              "\"nodes\":{" \
                "\"type\":\"array\"," \
                "\"minItems\":2," \
                "\"maxItems\":2," \
                "\"items\":{\"type\":\"string\"}" \
              "}," \
              "\"weight\":{\"type\":[\"number\",\"null\"]}," \
              "\"activation\":{\"type\":[\"number\",\"null\"]}" \
            "}" \
          "}" \
        "}" \
      "}" \
    "}," \
    "\"generalitati\":{" \
      "\"type\":\"object\"," \
      "\"additionalProperties\":false," \
      "\"required\":[\"nodes\",\"connections\"]," \
      "\"properties\":{" \
        "\"nodes\":{" \
          "\"type\":\"array\"," \
          "\"items\":{" \
            "\"type\":\"object\"," \
            "\"additionalProperties\":false," \
            "\"required\":[\"name\",\"weight\",\"activation\"]," \
            "\"properties\":{" \
              "\"name\":{\"type\":\"string\"}," \
              "\"weight\":{\"type\":[\"number\",\"null\"]}," \
              "\"activation\":{\"type\":[\"number\",\"null\"]}" \
            "}" \
          "}" \
        "}," \
        "\"connections\":{" \
          "\"type\":\"array\"," \
          "\"items\":{" \
            "\"type\":\"object\"," \
            "\"additionalProperties\":false," \
            "\"required\":[\"nodes\",\"weight\",\"activation\"]," \
            "\"properties\":{" \
              "\"nodes\":{" \
                "\"type\":\"array\"," \
                "\"minItems\":2," \
                "\"maxItems\":2," \
                "\"items\":{\"type\":\"string\"}" \
              "}," \
              "\"weight\":{\"type\":[\"number\",\"null\"]}," \
              "\"activation\":{\"type\":[\"number\",\"null\"]}" \
            "}" \
          "}" \
        "}" \
      "}" \
    "}," \
    "\"subiectiv\":{" \
      "\"type\":\"object\"," \
      "\"additionalProperties\":false," \
      "\"required\":[\"nodes\",\"connections\"]," \
      "\"properties\":{" \
        "\"nodes\":{" \
          "\"type\":\"array\"," \
          "\"items\":{" \
            "\"type\":\"object\"," \
            "\"additionalProperties\":false," \
            "\"required\":[\"name\",\"weight\",\"activation\"]," \
            "\"properties\":{" \
              "\"name\":{\"type\":\"string\"}," \
              "\"weight\":{\"type\":[\"number\",\"null\"]}," \
              "\"activation\":{\"type\":[\"number\",\"null\"]}" \
            "}" \
          "}" \
        "}," \
        "\"connections\":{" \
          "\"type\":\"array\"," \
          "\"items\":{" \
            "\"type\":\"object\"," \
            "\"additionalProperties\":false," \
            "\"required\":[\"nodes\",\"weight\",\"activation\"]," \
            "\"properties\":{" \
              "\"nodes\":{" \
                "\"type\":\"array\"," \
                "\"minItems\":2," \
                "\"maxItems\":2," \
                "\"items\":{\"type\":\"string\"}" \
              "}," \
              "\"weight\":{\"type\":[\"number\",\"null\"]}," \
              "\"activation\":{\"type\":[\"number\",\"null\"]}" \
            "}" \
          "}" \
        "}" \
      "}" \
    "}" \
  "}" \
"}"


void DecomposeInputIntoGraph(String *input);

#endif
